[default]
timeout = 60

[thoughtworks_insights]
title = "ThoughtWorks Insight Blogs"
url = "https://www.thoughtworks.com/en-gb/insights/blog"
entrySelector = ".cmp-content-card__text"
titleSelector = ".cmp-content-card__text__para-text"
linkSelector = "a"
contentSelector = ".cmp-content-card__text__para-text"
waitUntil = "networkidle"